"""Correcoes de seguranca e performance

Revision ID: 1d5a2a5462f3
Revises: 
Create Date: 2026-02-19 22:15:26.973990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d5a2a5462f3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('freelancers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('habilidades', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freelancers_cpf'), 'freelancers', ['cpf'], unique=True)
    op.create_index(op.f('ix_freelancers_id'), 'freelancers', ['id'], unique=False)
    op.create_index(op.f('ix_freelancers_nome'), 'freelancers', ['nome'], unique=False)
    op.create_index(op.f('ix_freelancers_user_id'), 'freelancers', ['user_id'], unique=True)
    op.create_table('notificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mensagem', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificacoes_id'), 'notificacoes', ['id'], unique=False)
    op.create_index(op.f('ix_notificacoes_status'), 'notificacoes', ['status'], unique=False)
    op.create_index(op.f('ix_notificacoes_user_id'), 'notificacoes', ['user_id'], unique=False)
    op.create_table('pagamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('plano_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('stripe_session_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('vagas_total', sa.Integer(), nullable=True),
    sa.Column('vagas_usadas', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_session_id')
    )
    op.create_index(op.f('ix_pagamentos_id'), 'pagamentos', ['id'], unique=False)
    op.create_table('vagas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('quantidade_candidaturas', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vagas_empresa_id'), 'vagas', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_vagas_id'), 'vagas', ['id'], unique=False)
    op.create_index(op.f('ix_vagas_status'), 'vagas', ['status'], unique=False)
    op.create_index(op.f('ix_vagas_titulo'), 'vagas', ['titulo'], unique=False)
    op.create_table('candidaturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vaga_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vaga_id'], ['vagas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidaturas_id'), 'candidaturas', ['id'], unique=False)
    op.create_index(op.f('ix_candidaturas_status'), 'candidaturas', ['status'], unique=False)
    op.create_index(op.f('ix_candidaturas_user_id'), 'candidaturas', ['user_id'], unique=False)
    op.create_index(op.f('ix_candidaturas_vaga_id'), 'candidaturas', ['vaga_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidaturas_vaga_id'), table_name='candidaturas')
    op.drop_index(op.f('ix_candidaturas_user_id'), table_name='candidaturas')
    op.drop_index(op.f('ix_candidaturas_status'), table_name='candidaturas')
    op.drop_index(op.f('ix_candidaturas_id'), table_name='candidaturas')
    op.drop_table('candidaturas')
    op.drop_index(op.f('ix_vagas_titulo'), table_name='vagas')
    op.drop_index(op.f('ix_vagas_status'), table_name='vagas')
    op.drop_index(op.f('ix_vagas_id'), table_name='vagas')
    op.drop_index(op.f('ix_vagas_empresa_id'), table_name='vagas')
    op.drop_table('vagas')
    op.drop_index(op.f('ix_pagamentos_id'), table_name='pagamentos')
    op.drop_table('pagamentos')
    op.drop_index(op.f('ix_notificacoes_user_id'), table_name='notificacoes')
    op.drop_index(op.f('ix_notificacoes_status'), table_name='notificacoes')
    op.drop_index(op.f('ix_notificacoes_id'), table_name='notificacoes')
    op.drop_table('notificacoes')
    op.drop_index(op.f('ix_freelancers_user_id'), table_name='freelancers')
    op.drop_index(op.f('ix_freelancers_nome'), table_name='freelancers')
    op.drop_index(op.f('ix_freelancers_id'), table_name='freelancers')
    op.drop_index(op.f('ix_freelancers_cpf'), table_name='freelancers')
    op.drop_table('freelancers')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
